-- Verify unity_manager:init on pg
BEGIN;

CREATE DOMAIN "hexColor" AS text
CHECK(
    value ~ '^#[a-fA-F0-9]{6}$'
);

CREATE TABLE "user" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "firstname" TEXT NOT NULL,
    "lastname" TEXT NOT NULL,
    "code_color" "hexColor" NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "project" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "owner_id" INT NOT NULL REFERENCES "user" ("id"),
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "list" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "position" FLOAT NOT NULL,
    "code_color" "hexColor" NOT NULL,
    "project_id" INT NOT NULL REFERENCES "project" ("id")  ON DELETE CASCADE ,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "card" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "position" FLOAT NOT NULL,
    "list_id" INT NOT NULL REFERENCES "list" ("id")  ON DELETE CASCADE ,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "project_has_user" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "project_id" INT NOT NULL REFERENCES "project" ("id") ON DELETE CASCADE,
    "user_id" INT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "tag" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "code_color" "hexColor" NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "card_has_tag" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tag_id" INT NOT NULL REFERENCES "tag" ("id"),
    "card_id" INT NOT NULL REFERENCES "card" ("id") ON DELETE CASCADE ,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "card_has_user" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" INT NOT NULL REFERENCES "user" ("id"),
    "card_id" INT NOT NULL REFERENCES "card" ("id") ON DELETE CASCADE,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ
);

COMMIT;